### ISSUE TITLE
policy object should contain a resource identifier

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#162]
policy object json should move to the below -

```json
"object": {
  "resource_id": "/"
}
```

**Comment by barinek** [comment]
we should include a second story for removing the existing resources[ ]
this one to add `resource_id`
the second to remove `resources[ ]`

**Comment by ggebel** [comment]
@independentid  Does the platform identifier go here or somewhere else, like a terraform config?
