### ISSUE TITLE
idql policies should include a unique identifier

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#172]
policy should look like the below - and can be auto assigned by the provider

```json
{
  "policies": [
    {
      "id" : "anId",
      "meta": {
        "version": ""
      },
```

**Comment by barinek** [comment]
for example-
gcp: 97844480062942818
azure: 63a8614b-b5n7-00r8-af0a-157866fa7129

**Comment by barinek** [comment]
As discussed, we will need to auto generating a unique policy ID for each provider policy - and we have really no way to recreate the same ID each time we set/ get policy - any suggestions on how to handle this? we might need a bit more research here?

**Comment by ggebel** [comment]
Sounds like this topic ties into some of the discussions we've had on policy lifecycle. An example scenario:

- connect to target
- get policy
- create unique ID for policy
- change policy setting
- set policy in target system
- ... some time later
- get the same policy from target system
- do we check the authoritative source to see if policy ID matches (or if one exists)?

Ultimately, sounds like we need some more research on the topic, as you suggested @barinek

**Comment by barinek** [comment]
sounds good - as we do not store the policy or the newly generated unique id anywhere currently

**Comment by independentid** [comment]
The purpose of the id is two-fold:
* A permanent identifier to track a policy instance
* While the policy id does not change, the policy can change.  This enables change detection in particular.  
* Also useful if you want to build an API for policies, you could retrieve using GET /Policies/{id}
