### ISSUE TITLE
Display provider service subtype when listing applications

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#180]
On the Applications page, add the technology subtype column after the Provider. For example, this could be Kubernetes, app engine or other

**Comment by barinek** [comment]
we should also be able to remove any code similar to the below

`{{if eq .ProviderName "google_cloud"}}`

**Comment by barinek** [comment]
subtype may include app engine, kubernetes (gke, aks, eks), elastic container service
also, platform name should also be on show page

**Comment by wfernandes** [comment]
https://github.com/hexa-org/policy-orchestrator/pull/240

This PR adds specific service types for applications retrieved from the different providers. Below is a list of Providers and the supported service types.

- Google Cloud Platform:
  - AppEngine
  - Kubernetes
- Azure Cloud Platform:
  - App Service
- Open Policy Agent:
  - Hexa OPA
- Amazon Web Services:
  - Cognito

The service type now shows up as a column in the List Applications page and the Show Application Details page.
