### ISSUE TITLE
Postgres database should support TLS

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#191]
there should be a few examples for postgresql. seems straight forward on the surface. we should ensure this works with docker-compose as well for local demonstrations.

**Comment by barinek** [comment]
to test, change the docker connection string -
```
POSTGRESQL_URL: postgres://orchestrator:orchestrator@postgresql:5432/orchestrator_development?sslmode=disable
```
the orchestrator should still work
then, look for and comment out the below in the local `.postgres/pg_hba.conf` directory
```
#host all all all scram-sha-256
```
the orchestrator should not work anymore.
finally, undo the `POSTGRESQL_URL` above.
the orchestrator should work again

**Comment by ggebel** [comment]
Accepting this story for now, we'll add another story that enhances status health check so that the database status is clearly displayed
