### ISSUE TITLE
Decision support library should determine protocol from request

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#193]
the method is currently hard coded for demonstration purposes - an incremental step toward current the idql version -

```go
	return OpaQuery{map[string]interface{}{
		"method":    "http:GET:" +
```

**Comment by barinek** [comment]
to test - change a policy action to "https:GET:" and then attempt a http request

**Comment by ggebel** [comment]
@barinek After changing the policy to "https", I get access denied for the resource - is that the expected behavior?
