### ISSUE TITLE
include a database health check for the orchestrator

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#202]
we should return an indication via both admin and orchestrator that the database connection is healthy

**Comment by barinek** [comment]
here is the json string via the orchestrator -
```json
[{"name":"server","pass":"true"},{"name":"database","pass":"true"}]
```
the admin also includes a visual indicator under the status tab

**Comment by ggebel** [comment]
@barinek - Is this the expected behavior when commenting out db and migrate?



![Image](https://user-images.githubusercontent.com/83663628/180028345-6dfe0e82-8c89-4f61-8817-bf344bba55ad.png)
