### ISSUE TITLE
Understand basic policy management for an apigee reverse proxy

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#215]

**Comment by barinek** [comment]
After exploring the apigee management api, we should be able to accomplish basic policy management. A few challenges include - the variety of policies and then interacting with individual policies in conjunction with a new deployment. The deployment  or redeployment and versioning of the proxy once the policy is updated may need to be a distinct second step, and possibly unrelated to the policy orchestrator.

**Comment by barinek** [comment]
feedback - look for a small or simple example that may include role or group based access
