### ISSUE TITLE
move policy from one azure instance to another azure instance

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#218]

**Comment by barinek** [comment]
we might need a few more azure api stories, the current discovery method pulls in too many resources

**Comment by independentid** [comment]
Do we need a selector UI or import wizard?

**Comment by barinek** [comment]
here are the apps for testing -
https://canary-bank-auth.azure.hexaorchestration.cc/
https://hexa-demo.azure.hexaorchestration.cc/
