### ISSUE TITLE
Provide feedback on readme for first time contributor

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#224]
Always looking to improve the readme file for people who are downloading and building Hexa for the first time. 

Is the documentation complete, are we making assumptions that should be clarified and documented?

**Comment by coreyti** [comment]
Moving to "accept": the work is done in [PR 233](https://github.com/hexa-org/policy-orchestrator/pull/233), but deserves review before merging as it brings a number of utilities that may or may not be desired.

**Comment by ggebel** [comment]
Need to update the readme because OPA now uses TLS.
Remove this example section: {
  "bundle_url": "http://hexa-demo-config:8889/bundles/bundle.tar.gz",
  "project_id": "Hexa Industries"
}

And replace with example that has CA cert - and place this in a file
