### ISSUE TITLE
use assert.Panics for tests replacing manual recovery

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#227]
Have a better way to handle testing for system panics

**Comment by wfernandes** [comment]
We have a couple of instances in our tests where we use the `recover()` pattern to assert a function panics. Let's replace this pattern with `assert.Panics` to make the tests more readable.

**Comment by wfernandes** [comment]
I just committed this to `main` branch since it was a minor test refactor - https://github.com/hexa-org/policy-orchestrator/commit/fa53039c69ba25848f2eb75d244e8cefc620330b

**Comment by wfernandes** [comment]
@ggebel I made the commit above for this story. Basically, its a refactor to the tests so we just need to ensure that the tests pass.

**Comment by wfernandes** [comment]
Github action that ran for the commit showing that CI went green -  https://github.com/hexa-org/policy-orchestrator/actions/runs/3129783084
