### ISSUE TITLE
use `t.Setenv` over `os.Setenv` in tests

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#228]
In some of our tests we've been using `os.Setenv` to set env vars. Let's switch them out for `t.Setenv`.

**Comment by nitinmewar** [comment]
hey @ggebel, I want to work on this.

**Comment by wfernandes** [comment]
Go for it @nitinmewar

**Comment by ggebel** [comment]
Awesome @nitinmewar, thanks for contributing!
