### ISSUE TITLE
include project_name in opa integration file, use for integration and application name and/or name prefix

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#229]
we'll need something like the below to render the apps and integrations page by demo application deployment

```json
{
  "project_id": "google_cloud:something_fun",
  "bundle_url": "https://bundle-server",
  "ca_cert": "<json encoded cert here>"
}
```

we should also update the readme and create integration web page

**Comment by wfernandes** [comment]
@barinek LMK if you want to give the PR #236 a look else I can merge it in and work with @ggebel to accept it.

**Comment by wfernandes** [comment]
@ggebel Just add the `project_id` field to your OPA integration files and see the name on different views.
