### ISSUE TITLE
start commands for tests (e.g., `opa run --server`) should fail if port is already bound

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#230]
In development, if the services are running in Docker, the test runner will successfully start up shadow services, listening on the same ports. However, traffic is sent to the Docker instances, so test fail mysteriously.

**Comment by coreyti** [comment]
Acceptance:

```shell
docker-compose up # spin up services to listen on a desired port.
go test ./pkg/orchestratorproviders/openpolicyagent/opa_policy_test.go
```

...and witness the test fail with "Port 8887 is unavailable" message.

```shell
docker-compose down # spin down those services.
go test ./pkg/orchestratorproviders/openpolicyagent/opa_policy_test.go
```

...and witness the test pass.

**Comment by ggebel** [comment]
Hi @coreyti 

I get the test fail message in step 1:
2022/10/04 14:17:59 Port 8887 is unavailable: listen tcp :8887: bind: address already in use

but the command hangs after doing docker-compose down

**Comment by coreyti** [comment]
Good catch, @ggebel. @wfernandes and I have pushed up an alternative implementation. Give it another try and let us know how it goes.

**Comment by ggebel** [comment]
Ok @coreyti, I ran the tests again...

Getting a different kind of error now from both tests:

2022/10/05 15:11:21 Starting command: opa run --server --addr :8887
2022/10/05 15:11:21 Unable to start cmd exec: "opa": executable file not found in $PATH
FAIL	command-line-arguments	0.573s
FAIL

**Comment by ggebel** [comment]
Since this is an update for developers, I observed the functionality on Corey's machine
