### ISSUE TITLE
Hawk Authentication failing with postman (issue #261 from github issues)

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#271]
See the issue posted here:
https://github.com/hexa-org/policy-orchestrator/issues/261

posted fix for this issue here:

https://github.com/hexa-org/policy-orchestrator/issues/261

**Comment by barinek** [comment]
let's update developer.md with postman section

**Comment by saurabh-io** [comment]
DEVELOPMENT.md updated and pushed to main

https://github.com/hexa-org/policy-orchestrator/blob/main/DEVELOPMENT.md#task-orchestrator-endpoints-via-postman

**Comment by saurabh-io** [comment]
Reviewed by @MrOrangeAndHam
