### ISSUE TITLE
Remove or fix dev/pkg scripts

### ISSUE THREAD

**Issue by wfernandes** [hexa-org/policy-orchestrator#277]
The dev/pkg scripts as described in DEVELOPMENT.md don't work on Linux machines. They also require some pre-requisites installed that only work on Mac OS.

The scripts add an additional footprint of maintenance and I'm not sure how often they are used.

Do we want to keep maintaining them or shall we remove them all together?

**Comment by independentid** [comment]
As part of migration to Chainguard and dockerfile, will attempt to simplify.

Seems to be an issue with how postgresql works in linux.  The dev setup scripts only work when running against a local service (ie. brew service). The dev set up will eventually install the "orchestrator_test" database which is needed to run go test modules.

Note also that I thnk these scripts are integrated into github CI scripting.

**Comment by independentid** [comment]
This was done as part of Issue #416.
