### ISSUE TITLE
Sort Applications list based on Provider, not Service

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#288]
Applications are sorted by "Service" and this can cause entries from multiple platforms to be split up (see screen cap below). Instead, we should sort by "Provider" so that all app resources from a platform are grouped together.

![Image](https://user-images.githubusercontent.com/83663628/221261377-80a88f4f-71c5-4088-a10c-32197dd82479.png)

**Comment by ghubrakesh** [comment]
Hello @ggebel, I would like to work on this problem, kindly assign it to me.

**Comment by ggebel** [comment]
Ok @ghubrakesh, here you go. Reach out if you have any questions

**Comment by Tikkitai** [comment]
Hello @ggebel , I don't know if you have heard anything back from ghubreksh but I would like to work on this if there is still work to be done! 

Thanks, Tikkitai

**Comment by ghubrakesh** [comment]
@Tikkitai yeah, I am currently busy with something. You can take it over :)

**Comment by Tikkitai** [comment]
I am actually going to have to give this up again, I seem to be having an issue with my Go Installation and the building of the Pack. Sorry about this

**Comment by ghubrakesh** [comment]
I am sorry @Tikkitai, I am also unable to complete this task. You can assign it to someone else.

**Comment by ggebel** [comment]
Ok, we will keep this issue open for now and there is no rush to complete it so one of you can come back at a later time to work on it - thanks again

**Comment by jingchu000** [comment]
Is this sorting on the front end?

**Comment by ggebel** [comment]
ok @jingchu000 I have assigned it to you. Please let us know when you are finished and we will review the PR

**Comment by jingchu000** [comment]
@ggebel Thank you. I have completed it. Please help me review the PR

**Comment by ggebel** [comment]
Great @jingchu000, we will take a look on Monday
