### ISSUE TITLE
Inconsistent PolicyInfo structs blocking hexa-mapper upgrade

### ISSUE THREAD

**Issue by independentid** [hexa-org/policy-orchestrator#295]
policy-orchestrator has duplicate and incompatible definitions for idql policy under the following:
* /internal/orchestrator/applications_handler.go
* /internal/policysupport/policy_support.go

This needs to converted to policysupport before we can integrate new policy-mapper pkg/hexamapper/hexa_policy.go which is designed as a compatible replacement for policy_support and includes the new ConditionInfo object for ABAC support

In particular the definition of Actions and ActionInfo is different.

**Comment by ggebel** [comment]
Hey @barinek, can you take a look at this?

**Comment by independentid** [comment]
Taking a look it appears that orchestrator/applications_handler.go is parsing based on the old Policies stuct and then switches to policysupport.PolicyInfo.   Normally this would be inconsequential unless an Action was defined.  

If this is correct, I can remove the old Policy code and switch over to PolicyInfo and add an aditional test case for ActionInfo.

This would make it much easier to swap in the hexa-mapper variant which upgrades PolicyInfo structs.

**Comment by independentid** [comment]
I have a fix and will post shortly.

**Comment by independentid** [comment]
This was completed in Issue #403
