### ISSUE TITLE
Create AWS tenant with Cognito

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#315]

**Comment by saurabh-io** [comment]
Created Cognito user pool in us-west-1

- Login to AWS account
- Navigate to Cognito
- Open the user pool "hexademo-canarybank-user-pool"
- Create a new user with your email
- An email will be sent to your inbox with a temporary password.
- Open https://canarybank.hexademo.org in a browser
- Click the sign-in with OIDC button.
- Login with your email and temporary password
- You will be asked to reset your password.
- Once reset done, you will land on the canarybank page.
