### ISSUE TITLE
fork Canary 2.0 demo application

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#320]

**Comment by saurabh-io** [comment]
Deployed canarybank-oidc-v2 to AWS with cognito authn

Steps for acceptance
- First time
  - Create user in cognito with your email
  - Open the invitation email with temporary password
- Navigate to https://canarybank.hexademo.org
- Click button Sign-in with OIDC
- Login with email and temporary password (if first time), or regular password.
- If first time accessing, you will be asked to reset password
- After password reset, you will land on the canarybank app
- Click links on left side
