### ISSUE TITLE
Implement Authz for CanaryBank API via AWS policy

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#343]
You must ~~be a member of specific role(s)~~ have authorization via AWS IAM Policies to access pages in the canary bank application

**Comment by saurabh-io** [comment]
Login to https://canarybank-aws.hexademo.org with Cognito
Try to access any page and you should get the "you do not have permissions" page.
Add a policy to AWS DynamoDB granting your cognito userId GET /developer
Access the developer page, and it should succeed.

You can repeat above two steps for /profile, /analytics, /humanresources
Notes: 
Only GET action is currently supported
Wildcards are not yet supported (e.g. /humanresources/*)
