### ISSUE TITLE
Deploy demo app to Azure behind enterprise integration

### ISSUE THREAD

**Issue by ggebel** [hexa-org/policy-orchestrator#52]

**Comment by gnarargs** [comment]
@ggebel You should be able to access the app after giving the app permission to read your data here https://hexa-demo.azurewebsites.net/

**Comment by ggebel** [comment]
@gnarargs I am getting this error on login:
AADSTS50020: User account 'gerry@strataidentityinc.onmicrosoft.com' from identity provider 'https://sts.windows.net/d4c8e5d6-22e8-42d3-bdf7-c3a61caabf36/' does not exist in tenant 'Strata Identity' and cannot access the application '46472ee2-1cfe-48ff-a495-a6e6e8d68733'(hexa-demo) in that tenant. The account needs to be added as an external user in the tenant first. Sign out and sign in again with a different Azure Active Directory user account.

**Comment by ggebel** [comment]
I was able to log in once I set my pwd in Azure AD
